#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 25 12:30:34 2022

@author: west
"""
import difflib
import glob
import os
import pandas as pd

Results_dir="/home/west/Projects/CAMELS/CAMELS_Files_Ngen/"
Folder=["camels_07301410_13754363","camels_04063700_6844165"]
Folder=["camels_04063700_6844165"]

for j in range(0,len(Folder)):
    all_results=glob.glob(Results_dir+Folder[j]+"/series_out/CFE/"+"cat*.csv")
    Diff=[]
    for i in range(0,len(all_results)):
        
        cat=os.path.basename(all_results[i])
        Series=Results_dir+Folder[j]+"/series_out/CFE/"+cat
        Para=Results_dir+Folder[j]+"/paral_out/CFE/"+cat
        
        with open(Series) as file_1:
            file_1_text = file_1.readlines()
          
        with open(Para) as file_2:
            file_2_text = file_2.readlines()
          
        # Find and print the diff:
        for line in difflib.unified_diff(
                file_1_text, file_2_text, fromfile='file1.txt', 
                tofile='file2.txt', lineterm=''):
            Diff.append([Folder[j],cat,line])
            #print(line)
    Diff_df=pd.DataFrame(data=Diff)
    Diff_df.to_csv(Results_dir+Folder[j]+"/"+Folder[j]+"Diff_para_series.csv")
    